bf16: true
cutoff_len: 16384
dataset: dpo_mix_en
dataset_dir: /home/gxhe/workspace/rl-train/data
ddp_timeout: 180000000
deepspeed: cache/ds_z3_config.json
do_train: true
finetuning_type: full
flash_attn: auto
gradient_accumulation_steps: 2
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: /home/gxhe/models/sft/3-0
num_train_epochs: 1.0
optim: adamw_torch
output_dir: saves/Yi-1.5-9B-Chat/full/train_2024-11-18-08-51-33
packing: false
per_device_train_batch_size: 1
plot_loss: true
pref_beta: 0.1
pref_ftx: 0
pref_loss: sigmoid
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: dpo
template: yi
warmup_steps: 0
